
// Function to fetch JSON data
async function fetchJsonData(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch JSON: ${response.statusText}`);
  }
  return response.json();
}

// URL of the external JSON file
const jsonUrl = 'pot.json';  // Replace with the actual path to your JSON file

// Fetch JSON data
fetchJsonData(jsonUrl)
  .then(variableArray => {
    // Create an object to hold variables
    const variablesObject = {};

    // Display variables in the HTML and populate the variables object
    //const variablesList = document.getElementById('variablesList');
    variableArray.forEach(variable => {
      const listItem = document.createElement('li');
      listItem.textContent = `${variable.key}: ${JSON.stringify(variable.value)}`;
      variablesList.appendChild(listItem);

      // Populate the variables object
      variablesObject[variable.key] = variable.value;
    });

    // Print the value of the variable with the key "h1"
    console.log(`Value of variable with key "h1": ${variablesObject.h1}`);

    // Assign the value of the variable with the key "celsius_value_c" to the JavaScript variable
    const celsius_value_c = variablesObject.celsius_value_c;
    console.log(`Value of celsius_value_c: ${celsius_value_c}`);
    const wind_d_value_c = variablesObject.wind_d_value_c;
    console.log(`Value of celsius_value_c: ${wind_d_value_c}`);
    const wind_b_mps_value_c = variablesObject.wind_b_value_c;
    console.log(`Value of celsius_value_c: ${wind_b_mps_value_c}`);
    const wind_b_k_value_c = variablesObject.wind_b_k_value_c;
    console.log(`Value of celsius_value_c: ${wind_b_k_value_c}`);
    const wind_g_mps_value_c = variablesObject.wind_g_value_c;
    console.log(`Value of celsius_value_c: ${wind_g_mps_value_c}`);
    const wind_g_k_value_c = variablesObject.wind_g_k_value_c;
    console.log(`Value of celsius_value_c: ${wind_g_k_value_c}`);
    const wind_bf_value_c = variablesObject.wind_bf_value_c;
    console.log(`Value of celsius_value_c: ${wind_bf_value_c}`);
    // hour 1
   const celsius_value_h1 =variablesObject.celsius_value_h1;
   console.log(`Value of celsius_value_h1: ${celsius_value_h1}`);
   const wind_d_value_h1 = variablesObject.wind_d_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_d_value_h1}`);
   const wind_b_mps_value_h1 = variablesObject.wind_b_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_b_mps_value_h1}`);
   const wind_b_k_value_h1 = variablesObject.wind_b_k_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_b_k_value_h1}`);
   const wind_g_mps_value_h1 = variablesObject.wind_g_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_g_mps_value_h1}`);
   const wind_g_k_value_h1 = variablesObject.wind_g_k_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_g_k_value_h1}`);
   const wind_bf_value_h1 = variablesObject.wind_bf_value_h1;
   console.log(`Value of celsius_value_h1: ${wind_bf_value_h1}`);

   const celsius_value_h2 = variablesObject.celsius_value_h2;
   console.log(`Value of celsius_value_h2: ${celsius_value_h2}`);
   const wind_d_value_h2 = variablesObject.wind_d_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_d_value_h2}`);
   const wind_b_mps_value_h2 = variablesObject.wind_b_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_b_mps_value_h2}`);
   const wind_b_k_value_h2 = variablesObject.wind_b_k_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_b_k_value_h2}`);
   const wind_g_mps_value_h2 = variablesObject.wind_g_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_g_mps_value_h2}`);
   const wind_g_k_value_h2 = variablesObject.wind_g_k_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_g_k_value_h2}`);
   const wind_bf_value_h2 = variablesObject.wind_bf_value_h2;
   console.log(`Value of celsius_value_h2: ${wind_bf_value_h2}`);

// Repeat the pattern for _h3 to _h10
   const celsius_value_h3 = variablesObject.celsius_value_h3;
   console.log(`Value of celsius_value_h3: ${celsius_value_h3}`);
   const wind_d_value_h3 = variablesObject.wind_d_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_d_value_h3}`);
   const wind_b_mps_value_h3 = variablesObject.wind_b_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_b_mps_value_h3}`);
   const wind_b_k_value_h3 = variablesObject.wind_b_k_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_b_k_value_h3}`);
   const wind_g_mps_value_h3 = variablesObject.wind_g_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_g_mps_value_h3}`);
   const wind_g_k_value_h3 = variablesObject.wind_g_k_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_g_k_value_h3}`);
   const wind_bf_value_h3 = variablesObject.wind_bf_value_h3;
   console.log(`Value of celsius_value_h3: ${wind_bf_value_h3}`);
   const celsius_value_h4 = variablesObject.celsius_value_h4;
   console.log(`Value of celsius_value_c: ${celsius_value_h4}`);
   const wind_d_value_h4 = variablesObject.wind_d_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_d_value_h4}`);
   const wind_b_mps_value_h4 = variablesObject.wind_b_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_b_mps_value_h4}`);
   const wind_b_k_value_h4 = variablesObject.wind_b_k_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_b_k_value_h4}`);
   const wind_g_mps_value_h4 = variablesObject.wind_g_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_g_mps_value_h4}`);
   const wind_g_k_value_h4 = variablesObject.wind_g_k_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_g_k_value_h4}`);
   const wind_bf_value_h4 = variablesObject.wind_bf_value_h4;
   console.log(`Value of celsius_value_h4: ${wind_bf_value_h4}`);

   // Repeat the pattern for _h5 to _h13
   const celsius_value_h5 = variablesObject.celsius_value_h5;
   console.log(`Value of celsius_value_c: ${celsius_value_h5}`);
   const wind_d_value_h5 = variablesObject.wind_d_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_d_value_h5}`);
   const wind_b_mps_value_h5 = variablesObject.wind_b_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_b_mps_value_h5}`);
   const wind_b_k_value_h5 = variablesObject.wind_b_k_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_b_k_value_h5}`); 
   const wind_g_mps_value_h5 = variablesObject.wind_g_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_g_mps_value_h5}`);
   const wind_g_k_value_h5 = variablesObject.wind_g_k_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_g_k_value_h5}`);
   const wind_bf_value_h5 = variablesObject.wind_bf_value_h5;
   console.log(`Value of celsius_value_h5: ${wind_bf_value_h5}`);
   const celsius_value_h6 = variablesObject.celsius_value_h6;
   console.log(`Value of celsius_value_c: ${celsius_value_h6}`);
   const wind_d_value_h6 = variablesObject.wind_d_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_d_value_h6}`);
   const wind_b_mps_value_h6 = variablesObject.wind_b_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_b_mps_value_h6}`);
   const wind_b_k_value_h6 = variablesObject.wind_b_k_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_b_k_value_h6}`);
   const wind_g_mps_value_h6 = variablesObject.wind_g_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_g_mps_value_h6}`);
   const wind_g_k_value_h6 = variablesObject.wind_g_k_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_g_k_value_h6}`);
   const wind_bf_value_h6 = variablesObject.wind_bf_value_h6;
   console.log(`Value of celsius_value_h6: ${wind_bf_value_h6}`);
   
   const celsius_value_h7 = variablesObject.celsius_value_h7;
   console.log(`Value of celsius_value_c: ${celsius_value_h7}`);
   const wind_d_value_h7 = variablesObject.wind_d_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_d_value_h7}`);
   const wind_b_mps_value_h7 = variablesObject.wind_b_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_b_mps_value_h7}`);
   const wind_b_k_value_h7 = variablesObject.wind_b_k_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_b_k_value_h7}`);
   const wind_g_mps_value_h7 = variablesObject.wind_g_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_g_mps_value_h7}`);
   const wind_g_k_value_h7 = variablesObject.wind_g_k_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_g_k_value_h7}`);
   const wind_bf_value_h7 = variablesObject.wind_bf_value_h7;
   console.log(`Value of celsius_value_h7: ${wind_bf_value_h7}`);
   
   const celsius_value_h8 = variablesObject.celsius_value_h8;
   console.log(`Value of celsius_value_c: ${celsius_value_h8}`);
   const wind_d_value_h8 = variablesObject.wind_d_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_d_value_h8}`);
   const wind_b_mps_value_h8 = variablesObject.wind_b_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_b_mps_value_h8}`);
   const wind_b_k_value_h8 = variablesObject.wind_b_k_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_b_k_value_h8}`);
   const wind_g_mps_value_h8 = variablesObject.wind_g_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_g_mps_value_h8}`);
   const wind_g_k_value_h8 = variablesObject.wind_g_k_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_g_k_value_h8}`);
   const wind_bf_value_h8 = variablesObject.wind_bf_value_h8;
   console.log(`Value of celsius_value_h8: ${wind_bf_value_h8}`);
   
   const celsius_value_h9 = variablesObject.celsius_value_h9;
   console.log(`Value of celsius_value_c: ${celsius_value_h9}`);
   const wind_d_value_h9 = variablesObject.wind_d_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_d_value_h9}`);
   const wind_b_mps_value_h9 = variablesObject.wind_b_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_b_mps_value_h9}`);
   const wind_b_k_value_h9 = variablesObject.wind_b_k_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_b_k_value_h9}`);
   const wind_g_mps_value_h9 = variablesObject.wind_g_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_g_mps_value_h9}`);
   const wind_g_k_value_h9 = variablesObject.wind_g_k_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_g_k_value_h9}`);
   const wind_bf_value_h9 = variablesObject.wind_bf_value_h9;
   console.log(`Value of celsius_value_h9: ${wind_bf_value_h9}`);
   
   const celsius_value_h10 = variablesObject.celsius_value_h10;
   console.log(`Value of celsius_value_c: ${celsius_value_h10}`);
   const wind_d_value_h10 = variablesObject.wind_d_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_d_value_h10}`);
   const wind_b_mps_value_h10 = variablesObject.wind_b_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_b_mps_value_h10}`);
   const wind_b_k_value_h10 = variablesObject.wind_b_k_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_b_k_value_h10}`);
   const wind_g_mps_value_h10 = variablesObject.wind_g_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_g_mps_value_h10}`);
   const wind_g_k_value_h10 = variablesObject.wind_g_k_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_g_k_value_h10}`);
   const wind_bf_value_h10 = variablesObject.wind_bf_value_h10;
   console.log(`Value of celsius_value_h10: ${wind_bf_value_h10}`);
   
   const celsius_value_h11 = variablesObject.celsius_value_h11;
   console.log(`Value of celsius_value_c: ${celsius_value_h11}`);
   const wind_d_value_h11 = variablesObject.wind_d_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_d_value_h11}`);
   const wind_b_mps_value_h11 = variablesObject.wind_b_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_b_mps_value_h11}`);
   const wind_b_k_value_h11 = variablesObject.wind_b_k_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_b_k_value_h11}`);
   const wind_g_mps_value_h11 = variablesObject.wind_g_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_g_mps_value_h11}`);
   const wind_g_k_value_h11 = variablesObject.wind_g_k_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_g_k_value_h11}`);
   const wind_bf_value_h11 = variablesObject.wind_bf_value_h11;
   console.log(`Value of celsius_value_h11: ${wind_bf_value_h11}`);
   
   const celsius_value_h12 = variablesObject.celsius_value_h12;
   console.log(`Value of celsius_value_c: ${celsius_value_h12}`);
   const wind_d_value_h12 = variablesObject.wind_d_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_d_value_h12}`);
   const wind_b_mps_value_h12 = variablesObject.wind_b_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_b_mps_value_h12}`);
   const wind_b_k_value_h12 = variablesObject.wind_b_k_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_b_k_value_h12}`);
   const wind_g_mps_value_h12 = variablesObject.wind_g_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_g_mps_value_h12}`);
   const wind_g_k_value_h12 = variablesObject.wind_g_k_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_g_k_value_h12}`);
   const wind_bf_value_h12 = variablesObject.wind_bf_value_h12;
   console.log(`Value of celsius_value_h12: ${wind_bf_value_h12}`);
    
   const celsius_value_h13 = variablesObject.celsius_value_h13;
   console.log(`Value of celsius_value_c: ${celsius_value_h13}`);
   const wind_d_value_h13 = variablesObject.wind_d_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_d_value_h13}`);
   const wind_b_mps_value_h13 = variablesObject.wind_b_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_b_mps_value_h13}`);
   const wind_b_k_value_h13 = variablesObject.wind_b_k_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_b_k_value_h13}`);
   const wind_g_mps_value_h13 = variablesObject.wind_g_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_g_mps_value_h13}`);
   const wind_g_k_value_h13 = variablesObject.wind_g_k_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_g_k_value_h13}`);
   const wind_bf_value_h13 = variablesObject.wind_bf_value_h13;
   console.log(`Value of celsius_value_h13: ${wind_bf_value_h13}`);
   

    // day 2 
    const celsius_value_d2_h1 = variablesObject.celsius_value_d2_h1;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h1}`);
    const wind_d_value_d2_h1 = variablesObject.wind_d_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_d_value_d2_h1}`);
    const wind_b_mps_value_d2_h1 = variablesObject.wind_b_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_b_mps_value_d2_h1}`);
    const wind_b_k_value_d2_h1 = variablesObject.wind_b_k_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_b_k_value_d2_h1}`);
    const wind_g_mps_value_d2_h1 = variablesObject.wind_g_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_g_mps_value_d2_h1}`);
    const wind_g_k_value_d2_h1 = variablesObject.wind_g_k_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_g_k_value_d2_h1}`);
    const wind_bf_value_d2_h1 = variablesObject.wind_bf_value_d2_h1;
    console.log(`Value of celsius_value_h1: ${wind_bf_value_d2_h1}`);
    
    const celsius_value_d2_h2 = variablesObject.celsius_value_d2_h2;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h2}`);
    const wind_d_value_d2_h2 = variablesObject.wind_d_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_d_value_d2_h2}`);
    const wind_b_mps_value_d2_h2 = variablesObject.wind_b_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_b_mps_value_d2_h2}`);
    const wind_b_k_value_d2_h2 = variablesObject.wind_b_k_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_b_k_value_d2_h2}`);
    const wind_g_mps_value_d2_h2 = variablesObject.wind_g_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_g_mps_value_d2_h2}`);
    const wind_g_k_value_d2_h2 = variablesObject.wind_g_k_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_g_k_value_d2_h2}`);
    const wind_bf_value_d2_h2 = variablesObject.wind_bf_value_d2_h2;
    console.log(`Value of celsius_value_h2: ${wind_bf_value_d2_h2}`);
    
    const celsius_value_d2_h3 = variablesObject.celsius_value_d2_h3;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h3}`);
    const wind_d_value_d2_h3 = variablesObject.wind_d_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_d_value_d2_h3}`);
    const wind_b_mps_value_d2_h3 = variablesObject.wind_b_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_b_mps_value_d2_h3}`);
    const wind_b_k_value_d2_h3 = variablesObject.wind_b_k_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_b_k_value_d2_h3}`);
    const wind_g_mps_value_d2_h3 = variablesObject.wind_g_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_g_mps_value_d2_h3}`);
    const wind_g_k_value_d2_h3 = variablesObject.wind_g_k_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_g_k_value_d2_h3}`);
    const wind_bf_value_d2_h3 = variablesObject.wind_bf_value_d2_h3;
    console.log(`Value of celsius_value_h3: ${wind_bf_value_d2_h3}`);
    
    const celsius_value_d2_h4 = variablesObject.celsius_value_d2_h4;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h4}`);
    const wind_d_value_d2_h4 = variablesObject.wind_d_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_d_value_d2_h4}`);
    const wind_b_mps_value_d2_h4 = variablesObject.wind_b_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_b_mps_value_d2_h4}`);
    const wind_b_k_value_d2_h4 = variablesObject.wind_b_k_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_b_k_value_d2_h4}`);
    const wind_g_mps_value_d2_h4 = variablesObject.wind_g_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_g_mps_value_d2_h4}`);
    const wind_g_k_value_d2_h4 = variablesObject.wind_g_k_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_g_k_value_d2_h4}`);
    const wind_bf_value_d2_h4 = variablesObject.wind_bf_value_d2_h4;
    console.log(`Value of celsius_value_h4: ${wind_bf_value_d2_h4}`);
    
    const celsius_value_d2_h5 = variablesObject.celsius_value_d2_h5;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h5}`);
    const wind_d_value_d2_h5 = variablesObject.wind_d_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_d_value_d2_h5}`);
    const wind_b_mps_value_d2_h5 = variablesObject.wind_b_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_b_mps_value_d2_h5}`);
    const wind_b_k_value_d2_h5 = variablesObject.wind_b_k_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_b_k_value_d2_h5}`);
    const wind_g_mps_value_d2_h5 = variablesObject.wind_g_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_g_mps_value_d2_h5}`);
    const wind_g_k_value_d2_h5 = variablesObject.wind_g_k_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_g_k_value_d2_h5}`);
    const wind_bf_value_d2_h5 = variablesObject.wind_bf_value_d2_h5;
    console.log(`Value of celsius_value_h5: ${wind_bf_value_d2_h5}`);
    
    const celsius_value_d2_h6 = variablesObject.celsius_value_d2_h6;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h6}`);
    const wind_d_value_d2_h6 = variablesObject.wind_d_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_d_value_d2_h6}`);
    const wind_b_mps_value_d2_h6 = variablesObject.wind_b_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_b_mps_value_d2_h6}`);
    const wind_b_k_value_d2_h6 = variablesObject.wind_b_k_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_b_k_value_d2_h6}`);
    const wind_g_mps_value_d2_h6 = variablesObject.wind_g_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_g_mps_value_d2_h6}`);
    const wind_g_k_value_d2_h6 = variablesObject.wind_g_k_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_g_k_value_d2_h6}`);
    const wind_bf_value_d2_h6 = variablesObject.wind_bf_value_d2_h6;
    console.log(`Value of celsius_value_h6: ${wind_bf_value_d2_h6}`);
     

    const celsius_value_d2_h7 = variablesObject.celsius_value_d2_h7;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h7}`);
    const wind_d_value_d2_h7 = variablesObject.wind_d_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_d_value_d2_h7}`);
    const wind_b_mps_value_d2_h7 = variablesObject.wind_b_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_b_mps_value_d2_h7}`);
    const wind_b_k_value_d2_h7 = variablesObject.wind_b_k_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_b_k_value_d2_h7}`);
    const wind_g_mps_value_d2_h7 = variablesObject.wind_g_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_g_mps_value_d2_h7}`);
    const wind_g_k_value_d2_h7 = variablesObject.wind_g_k_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_g_k_value_d2_h7}`);
    const wind_bf_value_d2_h7 = variablesObject.wind_bf_value_d2_h7;
    console.log(`Value of celsius_value_h7: ${wind_bf_value_d2_h7}`);
    
    const celsius_value_d2_h8 = variablesObject.celsius_value_d2_h8;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h8}`);
    const wind_d_value_d2_h8 = variablesObject.wind_d_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_d_value_d2_h8}`);
    const wind_b_mps_value_d2_h8 = variablesObject.wind_b_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_b_mps_value_d2_h8}`);
    const wind_b_k_value_d2_h8 = variablesObject.wind_b_k_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_b_k_value_d2_h8}`);
    const wind_g_mps_value_d2_h8 = variablesObject.wind_g_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_g_mps_value_d2_h8}`);
    const wind_g_k_value_d2_h8 = variablesObject.wind_g_k_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_g_k_value_d2_h8}`);
    const wind_bf_value_d2_h8 = variablesObject.wind_bf_value_d2_h8;
    console.log(`Value of celsius_value_h8: ${wind_bf_value_d2_h8}`);
    
    const celsius_value_d2_h9 = variablesObject.celsius_value_d2_h9;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h9}`);
    const wind_d_value_d2_h9 = variablesObject.wind_d_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_d_value_d2_h9}`);
    const wind_b_mps_value_d2_h9 = variablesObject.wind_b_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_b_mps_value_d2_h9}`);
    const wind_b_k_value_d2_h9 = variablesObject.wind_b_k_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_b_k_value_d2_h9}`);
    const wind_g_mps_value_d2_h9 = variablesObject.wind_g_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_g_mps_value_d2_h9}`);
    const wind_g_k_value_d2_h9 = variablesObject.wind_g_k_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_g_k_value_d2_h9}`);
    const wind_bf_value_d2_h9 = variablesObject.wind_bf_value_d2_h9;
    console.log(`Value of celsius_value_h9: ${wind_bf_value_d2_h9}`);
    
    const celsius_value_d2_h10 = variablesObject.celsius_value_d2_h10;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h10}`);
    const wind_d_value_d2_h10 = variablesObject.wind_d_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_d_value_d2_h10}`);
    const wind_b_mps_value_d2_h10 = variablesObject.wind_b_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_b_mps_value_d2_h10}`);
    const wind_b_k_value_d2_h10 = variablesObject.wind_b_k_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_b_k_value_d2_h10}`);
    const wind_g_mps_value_d2_h10 = variablesObject.wind_g_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_g_mps_value_d2_h10}`);
    const wind_g_k_value_d2_h10 = variablesObject.wind_g_k_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_g_k_value_d2_h10}`);
    const wind_bf_value_d2_h10 = variablesObject.wind_bf_value_d2_h10;
    console.log(`Value of celsius_value_h10: ${wind_bf_value_d2_h10}`);
    
    const celsius_value_d2_h11 = variablesObject.celsius_value_d2_h11;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h11}`);
    const wind_d_value_d2_h11 = variablesObject.wind_d_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_d_value_d2_h11}`);
    const wind_b_mps_value_d2_h11 = variablesObject.wind_b_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_b_mps_value_d2_h11}`);
    const wind_b_k_value_d2_h11 = variablesObject.wind_b_k_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_b_k_value_d2_h11}`);
    const wind_g_mps_value_d2_h11 = variablesObject.wind_g_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_g_mps_value_d2_h11}`);
    const wind_g_k_value_d2_h11 = variablesObject.wind_g_k_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_g_k_value_d2_h11}`);
    const wind_bf_value_d2_h11 = variablesObject.wind_bf_value_d2_h11;
    console.log(`Value of celsius_value_h11: ${wind_bf_value_d2_h11}`);
    
    const celsius_value_d2_h12 = variablesObject.celsius_value_d2_h12;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h12}`);
    const wind_d_value_d2_h12 = variablesObject.wind_d_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_d_value_d2_h12}`);
    const wind_b_mps_value_d2_h12 = variablesObject.wind_b_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_b_mps_value_d2_h12}`);
    const wind_b_k_value_d2_h12 = variablesObject.wind_b_k_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_b_k_value_d2_h12}`);
    const wind_g_mps_value_d2_h12 = variablesObject.wind_g_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_g_mps_value_d2_h12}`);
    const wind_g_k_value_d2_h12 = variablesObject.wind_g_k_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_g_k_value_d2_h12}`);
    const wind_bf_value_d2_h12 = variablesObject.wind_bf_value_d2_h12;
    console.log(`Value of celsius_value_h12: ${wind_bf_value_d2_h12}`);
    
    const celsius_value_d2_h13 = variablesObject.celsius_value_d2_h13;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h13}`);
    const wind_d_value_d2_h13 = variablesObject.wind_d_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_d_value_d2_h13}`);
    const wind_b_mps_value_d2_h13 = variablesObject.wind_b_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_b_mps_value_d2_h13}`);
    const wind_b_k_value_d2_h13 = variablesObject.wind_b_k_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_b_k_value_d2_h13}`);
    const wind_g_mps_value_d2_h13 = variablesObject.wind_g_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_g_mps_value_d2_h13}`);
    const wind_g_k_value_d2_h13 = variablesObject.wind_g_k_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_g_k_value_d2_h13}`);
    const wind_bf_value_d2_h13 = variablesObject.wind_bf_value_d2_h13;
    console.log(`Value of celsius_value_h13: ${wind_bf_value_d2_h13}`);
    
    const celsius_value_d2_h14 = variablesObject.celsius_value_d2_h14;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h14}`);
    const wind_d_value_d2_h14 = variablesObject.wind_d_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_d_value_d2_h14}`);
    const wind_b_mps_value_d2_h14 = variablesObject.wind_b_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_b_mps_value_d2_h14}`);
    const wind_b_k_value_d2_h14 = variablesObject.wind_b_k_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_b_k_value_d2_h14}`);
    const wind_g_mps_value_d2_h14 = variablesObject.wind_g_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_g_mps_value_d2_h14}`);
    const wind_g_k_value_d2_h14 = variablesObject.wind_g_k_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_g_k_value_d2_h14}`);
    const wind_bf_value_d2_h14 = variablesObject.wind_bf_value_d2_h14;
    console.log(`Value of celsius_value_h14: ${wind_bf_value_d2_h14}`);
    
    const celsius_value_d2_h15 = variablesObject.celsius_value_d2_h15;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h15}`);
    const wind_d_value_d2_h15 = variablesObject.wind_d_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_d_value_d2_h15}`);
    const wind_b_mps_value_d2_h15 = variablesObject.wind_b_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_b_mps_value_d2_h15}`);
    const wind_b_k_value_d2_h15 = variablesObject.wind_b_k_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_b_k_value_d2_h15}`);
    const wind_g_mps_value_d2_h15 = variablesObject.wind_g_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_g_mps_value_d2_h15}`);
    const wind_g_k_value_d2_h15 = variablesObject.wind_g_k_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_g_k_value_d2_h15}`);
    const wind_bf_value_d2_h15 = variablesObject.wind_bf_value_d2_h15;
    console.log(`Value of celsius_value_h15: ${wind_bf_value_d2_h15}`);
    
    const celsius_value_d2_h16 = variablesObject.celsius_value_d2_h16;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h16}`);
    const wind_d_value_d2_h16 = variablesObject.wind_d_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_d_value_d2_h16}`);
    const wind_b_mps_value_d2_h16 = variablesObject.wind_b_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_b_mps_value_d2_h16}`);
    const wind_b_k_value_d2_h16 = variablesObject.wind_b_k_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_b_k_value_d2_h16}`);
    const wind_g_mps_value_d2_h16 = variablesObject.wind_g_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_g_mps_value_d2_h16}`);
    const wind_g_k_value_d2_h16 = variablesObject.wind_g_k_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_g_k_value_d2_h16}`);
    const wind_bf_value_d2_h16 = variablesObject.wind_bf_value_d2_h16;
    console.log(`Value of celsius_value_h16: ${wind_bf_value_d2_h16}`);
    
    const celsius_value_d2_h17 = variablesObject.celsius_value_d2_h17;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h17}`);
    const wind_d_value_d2_h17 = variablesObject.wind_d_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_d_value_d2_h17}`);
    const wind_b_mps_value_d2_h17 = variablesObject.wind_b_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_b_mps_value_d2_h17}`);
    const wind_b_k_value_d2_h17 = variablesObject.wind_b_k_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_b_k_value_d2_h17}`);
    const wind_g_mps_value_d2_h17 = variablesObject.wind_g_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_g_mps_value_d2_h17}`);
    const wind_g_k_value_d2_h17 = variablesObject.wind_g_k_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_g_k_value_d2_h17}`);
    const wind_bf_value_d2_h17 = variablesObject.wind_bf_value_d2_h17;
    console.log(`Value of celsius_value_h17: ${wind_bf_value_d2_h17}`);
    
    const celsius_value_d2_h18 = variablesObject.celsius_value_d2_h18;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h18}`);
    const wind_d_value_d2_h18 = variablesObject.wind_d_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_d_value_d2_h18}`);
    const wind_b_mps_value_d2_h18 = variablesObject.wind_b_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_b_mps_value_d2_h18}`);
    const wind_b_k_value_d2_h18 = variablesObject.wind_b_k_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_b_k_value_d2_h18}`);
    const wind_g_mps_value_d2_h18 = variablesObject.wind_g_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_g_mps_value_d2_h18}`);
    const wind_g_k_value_d2_h18 = variablesObject.wind_g_k_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_g_k_value_d2_h18}`);
    const wind_bf_value_d2_h18 = variablesObject.wind_bf_value_d2_h18;
    console.log(`Value of celsius_value_h18: ${wind_bf_value_d2_h18}`);
    
    const celsius_value_d2_h19 = variablesObject.celsius_value_d2_h19;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h19}`);
    const wind_d_value_d2_h19 = variablesObject.wind_d_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_d_value_d2_h19}`);
    const wind_b_mps_value_d2_h19 = variablesObject.wind_b_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_b_mps_value_d2_h19}`);
    const wind_b_k_value_d2_h19 = variablesObject.wind_b_k_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_b_k_value_d2_h19}`);
    const wind_g_mps_value_d2_h19 = variablesObject.wind_g_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_g_mps_value_d2_h19}`);
    const wind_g_k_value_d2_h19 = variablesObject.wind_g_k_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_g_k_value_d2_h19}`);
    const wind_bf_value_d2_h19 = variablesObject.wind_bf_value_d2_h19;
    console.log(`Value of celsius_value_h19: ${wind_bf_value_d2_h19}`);
    
    const celsius_value_d2_h20 = variablesObject.celsius_value_d2_h20;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h20}`);
    const wind_d_value_d2_h20 = variablesObject.wind_d_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_d_value_d2_h20}`);
    const wind_b_mps_value_d2_h20 = variablesObject.wind_b_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_b_mps_value_d2_h20}`);
    const wind_b_k_value_d2_h20 = variablesObject.wind_b_k_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_b_k_value_d2_h20}`);
    const wind_g_mps_value_d2_h20 = variablesObject.wind_g_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_g_mps_value_d2_h20}`);
    const wind_g_k_value_d2_h20 = variablesObject.wind_g_k_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_g_k_value_d2_h20}`);
    const wind_bf_value_d2_h20 = variablesObject.wind_bf_value_d2_h20;
    console.log(`Value of celsius_value_h20: ${wind_bf_value_d2_h20}`);
    
    const celsius_value_d2_h21 = variablesObject.celsius_value_d2_h21;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h21}`);
    const wind_d_value_d2_h21 = variablesObject.wind_d_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_d_value_d2_h21}`);
    const wind_b_mps_value_d2_h21 = variablesObject.wind_b_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_b_mps_value_d2_h21}`);
    const wind_b_k_value_d2_h21 = variablesObject.wind_b_k_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_b_k_value_d2_h21}`);
    const wind_g_mps_value_d2_h21 = variablesObject.wind_g_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_g_mps_value_d2_h21}`);
    const wind_g_k_value_d2_h21 = variablesObject.wind_g_k_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_g_k_value_d2_h21}`);
    const wind_bf_value_d2_h21 = variablesObject.wind_bf_value_d2_h21;
    console.log(`Value of celsius_value_h21: ${wind_bf_value_d2_h21}`);
    
    const celsius_value_d2_h22 = variablesObject.celsius_value_d2_h22;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h22}`);
    const wind_d_value_d2_h22 = variablesObject.wind_d_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_d_value_d2_h22}`);
    const wind_b_mps_value_d2_h22 = variablesObject.wind_b_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_b_mps_value_d2_h22}`);
    const wind_b_k_value_d2_h22 = variablesObject.wind_b_k_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_b_k_value_d2_h22}`);
    const wind_g_mps_value_d2_h22 = variablesObject.wind_g_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_g_mps_value_d2_h22}`);
    const wind_g_k_value_d2_h22 = variablesObject.wind_g_k_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_g_k_value_d2_h22}`);
    const wind_bf_value_d2_h22 = variablesObject.wind_bf_value_d2_h22;
    console.log(`Value of celsius_value_h22: ${wind_bf_value_d2_h22}`);
    
    const celsius_value_d2_h23 = variablesObject.celsius_value_d2_h23;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h23}`);
    const wind_d_value_d2_h23 = variablesObject.wind_d_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_d_value_d2_h23}`);
    const wind_b_mps_value_d2_h23 = variablesObject.wind_b_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_b_mps_value_d2_h23}`);
    const wind_b_k_value_d2_h23 = variablesObject.wind_b_k_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_b_k_value_d2_h23}`);
    const wind_g_mps_value_d2_h23 = variablesObject.wind_g_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_g_mps_value_d2_h23}`);
    const wind_g_k_value_d2_h23 = variablesObject.wind_g_k_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_g_k_value_d2_h23}`);
    const wind_bf_value_d2_h23 = variablesObject.wind_bf_value_d2_h23;
    console.log(`Value of celsius_value_h23: ${wind_bf_value_d2_h23}`);
    
    const celsius_value_d2_h24 = variablesObject.celsius_value_d2_h24;
    console.log(`Value of celsius_value_c: ${celsius_value_d2_h24}`);
    const wind_d_value_d2_h24 = variablesObject.wind_d_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_d_value_d2_h24}`);
    const wind_b_mps_value_d2_h24 = variablesObject.wind_b_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_b_mps_value_d2_h24}`);
    const wind_b_k_value_d2_h24 = variablesObject.wind_b_k_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_b_k_value_d2_h24}`);
    const wind_g_mps_value_d2_h24 = variablesObject.wind_g_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_g_mps_value_d2_h24}`);
    const wind_g_k_value_d2_h24 = variablesObject.wind_g_k_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_g_k_value_d2_h24}`);
    const wind_bf_value_d2_h24 = variablesObject.wind_bf_value_d2_h24;
    console.log(`Value of celsius_value_h24: ${wind_bf_value_d2_h24}`);
    // day 3 
     const celsius_value_d3_h1 = variablesObject.celsius_value_d3_h1;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h1}`);
const wind_d_value_d3_h1 = variablesObject.wind_d_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_d_value_d3_h1}`);
const wind_b_mps_value_d3_h1 = variablesObject.wind_b_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_b_mps_value_d3_h1}`);
const wind_b_k_value_d3_h1 = variablesObject.wind_b_k_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_b_k_value_d3_h1}`);
const wind_g_mps_value_d3_h1 = variablesObject.wind_g_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_g_mps_value_d3_h1}`);
const wind_g_k_value_d3_h1 = variablesObject.wind_g_k_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_g_k_value_d3_h1}`);
const wind_bf_value_d3_h1 = variablesObject.wind_bf_value_d3_h1;
console.log(`Value of celsius_value_h1: ${wind_bf_value_d3_h1}`);

const celsius_value_d3_h2 = variablesObject.celsius_value_d3_h2;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h2}`);
const wind_d_value_d3_h2 = variablesObject.wind_d_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_d_value_d3_h2}`);
const wind_b_mps_value_d3_h2 = variablesObject.wind_b_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_b_mps_value_d3_h2}`);
const wind_b_k_value_d3_h2 = variablesObject.wind_b_k_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_b_k_value_d3_h2}`);
const wind_g_mps_value_d3_h2 = variablesObject.wind_g_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_g_mps_value_d3_h2}`);
const wind_g_k_value_d3_h2 = variablesObject.wind_g_k_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_g_k_value_d3_h2}`);
const wind_bf_value_d3_h2 = variablesObject.wind_bf_value_d3_h2;
console.log(`Value of celsius_value_h2: ${wind_bf_value_d3_h2}`);

const celsius_value_d3_h3 = variablesObject.celsius_value_d3_h3;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h3}`);
const wind_d_value_d3_h3 = variablesObject.wind_d_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_d_value_d3_h3}`);
const wind_b_mps_value_d3_h3 = variablesObject.wind_b_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_b_mps_value_d3_h3}`);
const wind_b_k_value_d3_h3 = variablesObject.wind_b_k_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_b_k_value_d3_h3}`);
const wind_g_mps_value_d3_h3 = variablesObject.wind_g_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_g_mps_value_d3_h3}`);
const wind_g_k_value_d3_h3 = variablesObject.wind_g_k_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_g_k_value_d3_h3}`);
const wind_bf_value_d3_h3 = variablesObject.wind_bf_value_d3_h3;
console.log(`Value of celsius_value_h3: ${wind_bf_value_d3_h3}`);

const celsius_value_d3_h4 = variablesObject.celsius_value_d3_h4;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h4}`);
const wind_d_value_d3_h4 = variablesObject.wind_d_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_d_value_d3_h4}`);
const wind_b_mps_value_d3_h4 = variablesObject.wind_b_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_b_mps_value_d3_h4}`);
const wind_b_k_value_d3_h4 = variablesObject.wind_b_k_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_b_k_value_d3_h4}`);
const wind_g_mps_value_d3_h4 = variablesObject.wind_g_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_g_mps_value_d3_h4}`);
const wind_g_k_value_d3_h4 = variablesObject.wind_g_k_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_g_k_value_d3_h4}`);
const wind_bf_value_d3_h4 = variablesObject.wind_bf_value_d3_h4;
console.log(`Value of celsius_value_h4: ${wind_bf_value_d3_h4}`);

const celsius_value_d3_h5 = variablesObject.celsius_value_d3_h5;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h5}`);
const wind_d_value_d3_h5 = variablesObject.wind_d_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_d_value_d3_h5}`);
const wind_b_mps_value_d3_h5 = variablesObject.wind_b_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_b_mps_value_d3_h5}`);
const wind_b_k_value_d3_h5 = variablesObject.wind_b_k_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_b_k_value_d3_h5}`);
const wind_g_mps_value_d3_h5 = variablesObject.wind_g_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_g_mps_value_d3_h5}`);
const wind_g_k_value_d3_h5 = variablesObject.wind_g_k_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_g_k_value_d3_h5}`);
const wind_bf_value_d3_h5 = variablesObject.wind_bf_value_d3_h5;
console.log(`Value of celsius_value_h5: ${wind_bf_value_d3_h5}`);

const celsius_value_d3_h6 = variablesObject.celsius_value_d3_h6;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h6}`);
const wind_d_value_d3_h6 = variablesObject.wind_d_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_d_value_d3_h6}`);
const wind_b_mps_value_d3_h6 = variablesObject.wind_b_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_b_mps_value_d3_h6}`);
const wind_b_k_value_d3_h6 = variablesObject.wind_b_k_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_b_k_value_d3_h6}`);
const wind_g_mps_value_d3_h6 = variablesObject.wind_g_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_g_mps_value_d3_h6}`);
const wind_g_k_value_d3_h6 = variablesObject.wind_g_k_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_g_k_value_d3_h6}`);
const wind_bf_value_d3_h6 = variablesObject.wind_bf_value_d3_h6;
console.log(`Value of celsius_value_h6: ${wind_bf_value_d3_h6}`);

const celsius_value_d3_h7 = variablesObject.celsius_value_d3_h7;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h7}`);
const wind_d_value_d3_h7 = variablesObject.wind_d_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_d_value_d3_h7}`);
const wind_b_mps_value_d3_h7 = variablesObject.wind_b_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_b_mps_value_d3_h7}`);
const wind_b_k_value_d3_h7 = variablesObject.wind_b_k_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_b_k_value_d3_h7}`);
const wind_g_mps_value_d3_h7 = variablesObject.wind_g_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_g_mps_value_d3_h7}`);
const wind_g_k_value_d3_h7 = variablesObject.wind_g_k_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_g_k_value_d3_h7}`);
const wind_bf_value_d3_h7 = variablesObject.wind_bf_value_d3_h7;
console.log(`Value of celsius_value_h7: ${wind_bf_value_d3_h7}`);

const celsius_value_d3_h8 = variablesObject.celsius_value_d3_h8;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h8}`);
const wind_d_value_d3_h8 = variablesObject.wind_d_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_d_value_d3_h8}`);
const wind_b_mps_value_d3_h8 = variablesObject.wind_b_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_b_mps_value_d3_h8}`);
const wind_b_k_value_d3_h8 = variablesObject.wind_b_k_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_b_k_value_d3_h8}`);
const wind_g_mps_value_d3_h8 = variablesObject.wind_g_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_g_mps_value_d3_h8}`);
const wind_g_k_value_d3_h8 = variablesObject.wind_g_k_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_g_k_value_d3_h8}`);
const wind_bf_value_d3_h8 = variablesObject.wind_bf_value_d3_h8;
console.log(`Value of celsius_value_h8: ${wind_bf_value_d3_h8}`);

const celsius_value_d3_h9 = variablesObject.celsius_value_d3_h9;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h9}`);
const wind_d_value_d3_h9 = variablesObject.wind_d_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_d_value_d3_h9}`);
const wind_b_mps_value_d3_h9 = variablesObject.wind_b_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_b_mps_value_d3_h9}`);
const wind_b_k_value_d3_h9 = variablesObject.wind_b_k_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_b_k_value_d3_h9}`);
const wind_g_mps_value_d3_h9 = variablesObject.wind_g_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_g_mps_value_d3_h9}`);
const wind_g_k_value_d3_h9 = variablesObject.wind_g_k_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_g_k_value_d3_h9}`);
const wind_bf_value_d3_h9 = variablesObject.wind_bf_value_d3_h9;
console.log(`Value of celsius_value_h9: ${wind_bf_value_d3_h9}`);

const celsius_value_d3_h10 = variablesObject.celsius_value_d3_h10;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h10}`);
const wind_d_value_d3_h10 = variablesObject.wind_d_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_d_value_d3_h10}`);
const wind_b_mps_value_d3_h10 = variablesObject.wind_b_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_b_mps_value_d3_h10}`);
const wind_b_k_value_d3_h10 = variablesObject.wind_b_k_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_b_k_value_d3_h10}`);
const wind_g_mps_value_d3_h10 = variablesObject.wind_g_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_g_mps_value_d3_h10}`);
const wind_g_k_value_d3_h10 = variablesObject.wind_g_k_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_g_k_value_d3_h10}`);
const wind_bf_value_d3_h10 = variablesObject.wind_bf_value_d3_h10;
console.log(`Value of celsius_value_h10: ${wind_bf_value_d3_h10}`);

const celsius_value_d3_h11 = variablesObject.celsius_value_d3_h11;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h11}`);
const wind_d_value_d3_h11 = variablesObject.wind_d_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_d_value_d3_h11}`);
const wind_b_mps_value_d3_h11 = variablesObject.wind_b_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_b_mps_value_d3_h11}`);
const wind_b_k_value_d3_h11 = variablesObject.wind_b_k_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_b_k_value_d3_h11}`);
const wind_g_mps_value_d3_h11 = variablesObject.wind_g_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_g_mps_value_d3_h11}`);
const wind_g_k_value_d3_h11 = variablesObject.wind_g_k_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_g_k_value_d3_h11}`);
const wind_bf_value_d3_h11 = variablesObject.wind_bf_value_d3_h11;
console.log(`Value of celsius_value_h11: ${wind_bf_value_d3_h11}`);

const celsius_value_d3_h12 = variablesObject.celsius_value_d3_h12;
console.log(`Value of celsius_value_c: ${celsius_value_d3_h12}`);
const wind_d_value_d3_h12 = variablesObject.wind_d_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_d_value_d3_h12}`);
const wind_b_mps_value_d3_h12 = variablesObject.wind_b_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_b_mps_value_d3_h12}`);
const wind_b_k_value_d3_h12 = variablesObject.wind_b_k_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_b_k_value_d3_h12}`);
const wind_g_mps_value_d3_h12 = variablesObject.wind_g_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_g_mps_value_d3_h12}`);
const wind_g_k_value_d3_h12 = variablesObject.wind_g_k_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_g_k_value_d3_h12}`);
const wind_bf_value_d3_h12 = variablesObject.wind_bf_value_d3_h12;
console.log(`Value of celsius_value_h12: ${wind_bf_value_d3_h12}`);


    console.log('Variables displayed successfully!');
  })
  .catch(error => console.error(error));
